name: tensorflow
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - anyio=4.10.0=py310hca03da5_0
  - appnope=0.1.4=py310hca03da5_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=25.1.0=py310h254cc4a_0
  - asttokens=3.0.0=py310hca03da5_0
  - async-lru=2.0.5=py310hca03da5_0
  - attrs=25.4.0=py310hca03da5_2
  - babel=2.16.0=py310hca03da5_0
  - beautifulsoup4=4.13.5=py310hca03da5_0
  - bleach=6.2.0=py310hca03da5_0
  - brotlicffi=1.0.9.2=py310h50f4ffc_2
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py310h73c2a22_1
  - charset-normalizer=3.4.4=py310hca03da5_0
  - comm=0.2.1=py310hca03da5_0
  - debugpy=1.8.16=py310h50f4ffc_1
  - decorator=5.2.1=py310hca03da5_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - exceptiongroup=1.3.0=py310hca03da5_0
  - executing=2.2.1=py310hca03da5_0
  - expat=2.7.1=h313beb8_0
  - h11=0.16.0=py310hca03da5_1
  - httpcore=1.0.9=py310hca03da5_0
  - httpx=0.28.1=py310hca03da5_1
  - icu=75.1=hfee45f7_0
  - idna=3.11=py310hca03da5_0
  - ipykernel=6.30.1=py310hca03da5_0
  - ipython=8.30.0=py310hca03da5_0
  - jedi=0.19.2=py310hca03da5_0
  - jinja2=3.1.6=py310hca03da5_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - json5=0.9.25=py310hca03da5_0
  - jsonschema=4.25.0=py310hca03da5_1
  - jsonschema-specifications=2023.7.1=py310hca03da5_1
  - jupyter-lsp=2.2.5=py310hca03da5_0
  - jupyter_client=8.6.3=py310hca03da5_0
  - jupyter_core=5.8.1=py310hca03da5_0
  - jupyter_events=0.12.0=py310hca03da5_0
  - jupyter_server=2.16.0=py310hca03da5_0
  - jupyter_server_terminals=0.5.3=py310hca03da5_0
  - jupyterlab=4.4.7=py310hca03da5_0
  - jupyterlab_pygments=0.3.0=py310hca03da5_0
  - jupyterlab_server=2.28.0=py310hca03da5_0
  - libblas=3.9.0=38_h51639a9_openblas
  - libcblas=3.9.0=38_hb0561ab_openblas
  - libcxx=20.1.8=hd7fd590_1
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.4.4=hca03da5_1
  - libgfortran=15.2.0=hfcf01ff_1
  - libgfortran5=15.2.0=h742603c_1
  - liblapack=3.9.0=38_hd9741b5_openblas
  - liblzma=5.8.1=h39f12f2_2
  - liblzma-devel=5.8.1=h39f12f2_2
  - libopenblas=0.3.30=openmp_ha158390_3
  - libsodium=1.0.20=h897f8a9_0
  - libsqlite=3.51.0=h8adb53f_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=21.1.5=h4a912ad_2
  - matplotlib-inline=0.1.7=py310hca03da5_0
  - mistune=3.1.2=py310hca03da5_0
  - nbclient=0.10.2=py310hca03da5_0
  - nbconvert-core=7.16.6=py310hca03da5_0
  - nbformat=5.10.4=py310hca03da5_0
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=py310hca03da5_0
  - notebook=7.4.5=py310hca03da5_0
  - notebook-shim=0.2.4=py310hca03da5_0
  - openssl=3.6.0=h5503f6c_0
  - overrides=7.7.0=py310hca03da5_0
  - packaging=25.0=py310hca03da5_1
  - pandocfilters=1.5.1=py310hca03da5_0
  - parso=0.8.4=py310hca03da5_0
  - pexpect=4.9.0=py310hca03da5_1
  - platformdirs=4.5.0=py310hca03da5_0
  - prometheus_client=0.21.1=py310hca03da5_0
  - prompt-toolkit=3.0.52=py310hca03da5_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.0.0=py310haa24f5a_1
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pure_eval=0.2.3=py310hca03da5_0
  - pycparser=2.23=py310hca03da5_0
  - pygments=2.19.2=py310hca03da5_0
  - pysocks=1.7.1=py310hca03da5_1
  - python=3.10.19=hcd7f573_2_cpython
  - python-dateutil=2.9.0post0=py310hca03da5_2
  - python-fastjsonschema=2.20.0=py310hca03da5_0
  - python-json-logger=3.2.1=py310hca03da5_0
  - python_abi=3.10=8_cp310
  - pyyaml=6.0.2=py310h80987f9_0
  - pyzmq=27.1.0=py310h5a8c52c_1
  - readline=8.3=h0b18652_0
  - referencing=0.37.0=py310hca03da5_0
  - requests=2.32.5=py310hca03da5_1
  - rfc3339-validator=0.1.4=py310hca03da5_0
  - rfc3986-validator=0.1.1=py310hca03da5_0
  - rpds-py=0.28.0=py310h931abed_0
  - scikit-learn=1.3.2=py310h417b086_2
  - scipy=1.15.2=py310h32ab4ed_0
  - send2trash=1.8.2=py310hca03da5_1
  - setuptools=80.9.0=py310hca03da5_0
  - six=1.17.0=py310hca03da5_0
  - sniffio=1.3.0=py310hca03da5_0
  - soupsieve=2.5=py310hca03da5_0
  - sqlite=3.50.2=h79febb2_1
  - stack_data=0.6.3=py310hca03da5_0
  - terminado=0.18.1=py310hca03da5_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tinycss2=1.4.0=py310hca03da5_0
  - tk=8.6.15=hcd8a7d5_0
  - tomli=2.2.1=py310hca03da5_0
  - tornado=6.5.1=py310h80987f9_0
  - traitlets=5.14.3=py310hca03da5_0
  - typing_extensions=4.15.0=py310hca03da5_0
  - urllib3=2.5.0=py310hca03da5_0
  - wcwidth=0.2.13=py310hca03da5_0
  - webencodings=0.5.1=py310hca03da5_1
  - websocket-client=1.8.0=py310hca03da5_0
  - wheel=0.45.1=py310hca03da5_0
  - xz=5.8.1=h9a6d368_2
  - xz-gpl-tools=5.8.1=h9a6d368_2
  - xz-tools=5.8.1=h39f12f2_2
  - yaml=0.2.5=h1a28f6b_0
  - zeromq=4.3.5=h2c7f8f0_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - absl-py==2.3.1
      - astunparse==1.6.3
      - cachetools==6.2.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - gast==0.4.0
      - google-auth==2.41.1
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.74.0
      - h5py==3.15.1
      - keras==2.13.1
      - kiwisolver==1.4.9
      - libclang==18.1.1
      - markdown==3.9
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - ml-dtypes==0.2.0
      - namex==0.1.0
      - numpy==1.24.3
      - oauthlib==3.3.1
      - opencv-python==4.12.0.88
      - opt-einsum==3.4.0
      - optree==0.17.0
      - pandas==2.3.3
      - pillow==12.0.0
      - pip==25.3
      - protobuf==4.25.8
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pyparsing==3.2.5
      - pytz==2025.2
      - requests-oauthlib==2.0.0
      - rich==14.2.0
      - rsa==4.9.1
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.13.0
      - tensorflow-estimator==2.13.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflow-macos==2.13.0
      - termcolor==3.2.0
      - typing-extensions==4.5.0
      - tzdata==2025.2
      - werkzeug==3.1.3
      - wrapt==1.14.2
prefix: /opt/anaconda3/envs/tensorflow
